### ISSUE TITLE
"stable" box points to ynh 2.2

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost/ynh-dev#8]
… Instead of 2.4

**Comment by opi** [comment]
Maybe you have a previous vagrant box because latest boxes are Jessie+YNH 2.4, for sure.

I don't know if `vagrant box list` can help, or maybe you can try to remove existing boxes (`vagrant box remove yunohost/jessie-stable`) and add it again (`vagrant box add https://build.yunohost.org/yunohost-jessie-stable.box --name yunohost/jessie-stable`).

I'm not a vagrant expert, but maybe you can even try to upgrade your boxes (`vagrant box update`)

**Comment by JocelynDelalande** [comment]
opi <notifications@github.com> wrote:
> Maybe you have a previous vagrant box because latest boxes are
> Jessie+YNH 2.4, for sure.
> 
> I don't know if `vagrant box list` can help, or maybe you can
> try to remove existing boxes (`vagrant box remove
> yunohost/jessie-stable`) and add it again (`vagrant box add
> https://build.yunohost.org/yunohost-jessie-stable.box --name
> yunohost/jessie-stable`).
> 
> I'm not a vagrant expert, but maybe you can even try to upgrade
> your boxes (`vagrant box update`)

Ok, that's the kind of things I tried quickly, but as I was
confirmed on the jabber chan that I just opened this issue then.

I'll try again and report here (and enhance doc if relevant).

**Comment by JocelynDelalande** [comment]
Ooook, I was on the wrong branch with the vagrant repository. Thanks to opi's hints that's fixed.

Another issue was the lack of *vagrant* repository upgrade via `self-upgrade` commande, but @opi [didn't leave me the time to open a ticket](https://github.com/YunoHost/ynh-dev/commit/fd0332c57c0a899aa6eab8ab87eb9ca641adae57) <3.
